"""Shared-profile TOML compatibility, including opt-in real frontend startup."""

import json
import os
import subprocess
import tempfile
import unittest
from pathlib import Path

from marathon_app.codex_home import (
    LOCAL_CONFIG, SHARED_PROFILE_FILE, _shared_profile_text,
    codex_environment, prepare_codex_home, tomllib,
)

ROOT = Path(__file__).resolve().parents[1]
PROJECTS = {
    '/home/david': {'trust_level': 'trusted'},
    '/tmp/project with spaces/#notes.[v2]="quoted"': {'trust_level': 'untrusted'},
    '/tmp/café/雪\\backslash\ttab\nline': {'trust_level': 'trusted'},
}


def source_text(projects, settings=''):
    return settings + ''.join(
        f'\n[projects.{json.dumps(path, ensure_ascii=False)}]\n'
        f'trust_level = {json.dumps(entry["trust_level"])}\n'
        for path, entry in projects.items()
    )


class SharedProfileTests(unittest.TestCase):
    def test_missing_and_empty_source(self):
        with tempfile.TemporaryDirectory() as directory:
            source = Path(directory) / 'config.toml'
            self.assertEqual(tomllib.loads(_shared_profile_text(source)), LOCAL_CONFIG)
            source.write_text('')
            self.assertEqual(tomllib.loads(_shared_profile_text(source)), LOCAL_CONFIG)

    def test_project_tables_round_trip_and_root_settings_keep_their_scope(self):
        for projects in ({'/home/david': PROJECTS['/home/david']}, PROJECTS):
            with self.subTest(projects=projects), tempfile.TemporaryDirectory() as directory:
                source = Path(directory) / 'config.toml'
                source.write_text(source_text(projects))
                text = _shared_profile_text(source)
                parsed = tomllib.loads(text)
                self.assertEqual(parsed, dict(LOCAL_CONFIG, projects=projects))
                self.assertNotIn('projects = {', text)
                for path in projects:
                    self.assertIn(f'[projects.{json.dumps(path, ensure_ascii=False)}]', text)
                self.assertLess(text.index('features = '), text.index('[projects.'))

    def test_inherited_preferences_and_local_settings(self):
        with tempfile.TemporaryDirectory() as directory:
            source = Path(directory) / 'config.toml'
            source.write_text(source_text(PROJECTS, '''personality = "pragmatic"
model_verbosity = "low"
approval_policy = "on-request"
model = "do-not-inherit"
analytics = { enabled = true }
features = { apps = true }
''') + '\n[projects."/tmp/no-trust"]\nother_setting = "ignored"\n')
            parsed = tomllib.loads(_shared_profile_text(source))
            self.assertEqual(parsed, dict(LOCAL_CONFIG, projects=PROJECTS,
                                         personality='pragmatic', model_verbosity='low',
                                         approval_policy='on-request'))

    def test_existing_generated_files_are_repaired_without_changing_user_config(self):
        for old in (
            '# Generated by Marathon: local preferences only.\nprojects = { "/old" = { trust_level = "trusted" } }\n',
            '[# Generated by Marathon: local preferences only.\nprojects ]\n"/old" = { trust_level = "trusted" }\n',
        ):
            with self.subTest(old=old), tempfile.TemporaryDirectory() as directory:
                root = Path(directory)
                stock, local = root / 'stock', root / 'local'
                stock.mkdir()
                local.mkdir()
                original = source_text(PROJECTS)
                (stock / 'config.toml').write_text(original)
                local_config = 'model = "local-user-setting"\n'
                (local / 'config.toml').write_text(local_config)
                shared = local / SHARED_PROFILE_FILE
                shared.write_text(old)
                environment = {'CODEX_HOME': str(stock), 'MARATHON_CODEX_HOME': str(local)}
                prepare_codex_home(environment)
                self.assertEqual(tomllib.loads(shared.read_text()), dict(LOCAL_CONFIG, projects=PROJECTS))
                self.assertEqual(shared.stat().st_mode & 0o777, 0o600)
                modified = shared.stat().st_mtime_ns
                prepare_codex_home(environment)
                self.assertEqual(shared.stat().st_mtime_ns, modified)
                self.assertEqual((stock / 'config.toml').read_text(), original)
                self.assertEqual((local / 'config.toml').read_text(), local_config)
                self.assertFalse(shared.with_suffix('.toml.tmp').exists())

    @unittest.skipUnless(os.environ.get('MARATHON_TEST_CODEX_BIN'),
                         'Set MARATHON_TEST_CODEX_BIN to validate the real Codex loader')
    def test_real_codex_loader_accepts_generated_profiles(self):
        for projects in ({}, {'/home/david': PROJECTS['/home/david']}, PROJECTS):
            with self.subTest(projects=projects), tempfile.TemporaryDirectory() as directory:
                root = Path(directory)
                stock = root / 'stock'
                stock.mkdir()
                (stock / 'config.toml').write_text(source_text(projects, 'personality = "pragmatic"\n'))
                environment, home, profile = codex_environment(dict(
                    os.environ, MARATHON_STOCK_CODEX_HOME=str(stock),
                    MARATHON_CODEX_HOME=str(root / 'local'),
                ))
                result = subprocess.run([
                    os.environ['MARATHON_TEST_CODEX_BIN'], '--profile', profile,
                    '-c', 'model_provider="marathon-local"',
                    '-c', 'model_providers.marathon-local={name="Test",base_url="http://127.0.0.1:1/v1",wire_api="responses"}',
                    'mcp', 'list',
                ], cwd=root, env=environment, capture_output=True, text=True, timeout=30)
                self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
                self.assertEqual(tomllib.loads((home / SHARED_PROFILE_FILE).read_text()).get('projects', {}), projects)

    @unittest.skipUnless(os.environ.get('MARATHON_TEST_SHARED_PROFILE_GPU') == '1',
                         'Set MARATHON_TEST_SHARED_PROFILE_GPU=1 for live Marathon startup')
    def test_live_marathon_startup_and_trust_rewrite(self):
        with tempfile.TemporaryDirectory(prefix='marathon-shared-profile-') as directory:
            root = Path(directory)
            stock = root / 'stock'
            stock.mkdir()
            (stock / 'config.toml').write_text(source_text(PROJECTS))
            output = Path(os.environ.get('MARATHON_TEST_SHARED_PROFILE_OUTPUT', str(root / 'smoke')))
            result = subprocess.run([
                str(ROOT / 'bin/marathon'), 'eval', 'smoke', '--run-gpu',
                '--output-dir', str(output),
            ], env=dict(os.environ, MARATHON_STOCK_CODEX_HOME=str(stock),
                        MARATHON_CODEX_HOME=str(root / 'isolated')), capture_output=True,
                text=True, timeout=900)
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            results = json.loads((output / 'results.json').read_text())
            self.assertEqual(len(results), 5)
            self.assertTrue(all(row['passed'] for row in results))
            generated = list((output / 'codex-home').rglob(SHARED_PROFILE_FILE))
            self.assertTrue(generated)
            for path in generated:
                parsed = tomllib.loads(path.read_text())
                for project, entry in PROJECTS.items():
                    self.assertEqual(parsed['projects'][project], entry)
                self.assertEqual(parsed['features'], LOCAL_CONFIG['features'])
