"""Prepare an isolated Codex home for Marathon frontends."""

from __future__ import annotations

import json
import os
import shutil
import uuid
try:
    import tomllib
except ModuleNotFoundError:
    import tomli as tomllib
from pathlib import Path
from typing import Mapping

from .instance import instance_path, normalize_instance_name


ROOT_DIR = Path(__file__).resolve().parents[1]
SHARED_PROFILE = "marathon-shared"
SHARED_PROFILE_FILE = f"{SHARED_PROFILE}.config.toml"
SESSION_MIGRATION_MARKER = ".stock-marathon-sessions-migrated-v2"
MARATHON_SESSION_PROVIDERS = frozenset({"marathon-local", "marathon_local"})
SHARED_PATHS = (
    "AGENTS.md",
    "rules",
    "skills",
)
SHARED_CONFIG_KEYS = (
    "personality", "model_verbosity", "approval_policy", "sandbox_mode",
    "tool_output_token_limit", "project_doc_max_bytes", "project_doc_fallback_filenames",
)
LOCAL_CONFIG = {
    "check_for_update_on_startup": False,
    "cli_auth_credentials_store": "file",
    "analytics": {"enabled": False},
    "feedback": {"enabled": False},
    "otel": {"exporter": "none", "trace_exporter": "none", "metrics_exporter": "none"},
    "features": {
        "apps": False, "plugins": False, "remote_plugin": False,
        "tool_suggest": False, "recommended_plugins": False,
        "hooks": False, "plugin_hooks": False,
    },
}


def _toml_value(value) -> str:
    if isinstance(value, dict):
        return "{ " + ", ".join(
            f"{json.dumps(key, ensure_ascii=False)} = {_toml_value(item)}"
            for key, item in value.items()
        ) + " }"
    return json.dumps(value, ensure_ascii=False)


def stock_codex_home(environment: Mapping[str, str] | None = None) -> Path:
    """Return the user's normal Codex home, never Marathon's isolated override."""

    environment = os.environ if environment is None else environment
    configured = environment.get("MARATHON_STOCK_CODEX_HOME")
    if configured:
        return Path(configured).expanduser().resolve()
    configured = environment.get("CODEX_HOME")
    marathon_home = marathon_codex_home(environment)
    if configured:
        candidate = Path(configured).expanduser().resolve()
        if candidate != marathon_home and marathon_home not in candidate.parents:
            return candidate
    return (Path.home() / ".codex").resolve()


def marathon_codex_home(
    environment: Mapping[str, str] | None = None,
    instance: str | None = None,
) -> Path:
    """Return Marathon's writable Codex state root."""

    environment = os.environ if environment is None else environment
    name = normalize_instance_name(instance)
    configured = environment.get("MARATHON_CODEX_HOME")
    if configured:
        root = Path(configured).expanduser().resolve()
    else:
        root = (ROOT_DIR / ".marathon" / "codex-home").resolve()
    return instance_path(root, name)


def _path_present(path: Path) -> bool:
    return path.exists() or path.is_symlink()


def _share_path(source: Path, destination: Path) -> None:
    if not source.exists():
        return
    if not _path_present(destination):
        destination.symlink_to(source, target_is_directory=source.is_dir())
        return
    if source.is_dir() and destination.is_dir() and not destination.is_symlink():
        for child in source.iterdir():
            _share_path(child, destination / child.name)
        return


def _shared_profile_text(source: Path) -> str:
    try:
        data = tomllib.loads(source.read_text(encoding="utf-8"))
    except FileNotFoundError:
        data = {}
    # Inherit preferences, not executable startup integrations or account state.
    selected = {key: data[key] for key in SHARED_CONFIG_KEYS if key in data}
    selected["projects"] = {
        path: {"trust_level": entry["trust_level"]}
        for path, entry in data.get("projects", {}).items()
        if "trust_level" in entry
    }
    selected.update(LOCAL_CONFIG)
    return "# Generated by Marathon: local preferences only.\n" + "".join(
        f"{key} = {_toml_value(value)}\n" for key, value in selected.items()
    )


def _write_shared_profile(stock_home: Path, isolated_home: Path) -> None:
    destination = isolated_home / SHARED_PROFILE_FILE
    content = _shared_profile_text(stock_home / "config.toml")
    try:
        if destination.read_text(encoding="utf-8") == content:
            return
    except OSError:
        pass
    temporary = destination.with_suffix(destination.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.chmod(0o600)
    temporary.replace(destination)


def _session_provider(path: Path) -> str | None:
    try:
        with path.open(encoding="utf-8") as handle:
            for _ in range(32):
                line = handle.readline()
                if not line:
                    break
                item = json.loads(line)
                if item.get("type") == "session_meta":
                    payload = item.get("payload") or {}
                    provider = payload.get("model_provider")
                    return str(provider) if provider else None
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return None
    return None


def _normalize_legacy_session_provider(path: Path) -> bool:
    temporary = path.with_suffix(path.suffix + ".provider.tmp")
    normalized = False
    try:
        source_stat = path.stat()
        with path.open("rb") as source, temporary.open("wb") as destination:
            for raw in source:
                if not normalized:
                    try:
                        item = json.loads(raw)
                    except (UnicodeDecodeError, json.JSONDecodeError):
                        item = None
                    if isinstance(item, dict) and item.get("type") == "session_meta":
                        payload = item.get("payload") or {}
                        if payload.get("model_provider") == "marathon_local":
                            payload["model_provider"] = "marathon-local"
                            item["payload"] = payload
                            raw = (
                                json.dumps(item, ensure_ascii=False, separators=(",", ":"))
                                + "\n"
                            ).encode("utf-8")
                            normalized = True
                destination.write(raw)
        temporary.chmod(source_stat.st_mode & 0o777)
        os.utime(temporary, ns=(source_stat.st_atime_ns, source_stat.st_mtime_ns))
        temporary.replace(path)
    except OSError:
        return False
    finally:
        temporary.unlink(missing_ok=True)
    return normalized


def _migrate_marathon_sessions(stock_home: Path, isolated_home: Path) -> None:
    """Move existing Marathon rollouts out of stock Codex's session store."""

    marker = isolated_home / SESSION_MIGRATION_MARKER
    source_root = stock_home / "sessions"
    destination_root = isolated_home / "sessions"
    if marker.exists() or stock_home == isolated_home or not source_root.is_dir():
        return

    unresolved = False
    for source in source_root.rglob("*.jsonl"):
        provider = _session_provider(source)
        if provider not in MARATHON_SESSION_PROVIDERS:
            continue
        if provider == "marathon_local" and not _normalize_legacy_session_provider(source):
            unresolved = True
            continue
        destination = destination_root / source.relative_to(source_root)
        destination.parent.mkdir(parents=True, exist_ok=True)
        if _path_present(destination):
            unresolved = True
            continue
        try:
            source.replace(destination)
        except OSError:
            try:
                shutil.move(str(source), str(destination))
            except OSError:
                unresolved = True
                continue
    if not unresolved:
        marker.touch()


def prepare_codex_home(
    environment: Mapping[str, str] | None = None,
    instance: str | None = None,
) -> tuple[Path, str | None]:
    """Create Marathon's Codex boundary and return its home and base profile."""

    environment = os.environ if environment is None else environment
    name = normalize_instance_name(instance)
    stock_home = stock_codex_home(environment)
    if environment.get("MARATHON_USE_USER_CONFIG") == "1":
        raise RuntimeError("MARATHON_USE_USER_CONFIG bypasses local isolation and is no longer supported")

    isolated_home = marathon_codex_home(environment, name)
    if isolated_home == stock_home or stock_home in isolated_home.parents:
        raise RuntimeError("Marathon's home must be separate from the stock Codex home")
    isolated_home.mkdir(parents=True, exist_ok=True)
    isolated_home.chmod(0o700)
    for shared_name in ("auth.json", "hooks.json", "plugins"):
        destination = isolated_home / shared_name
        if destination.is_symlink() and destination.resolve() == (stock_home / shared_name).resolve():
            # Remove only Marathon's old link. The stock resource is untouched.
            destination.unlink()
        elif _path_present(destination):
            # Preserve locally owned state, but take it out of automatic discovery.
            destination.rename(isolated_home / f"{shared_name}.disabled-{uuid.uuid4().hex}")
    for shared_name in SHARED_PATHS:
        source = stock_home / shared_name
        destination = isolated_home / shared_name
        _share_path(source, destination)
    _write_shared_profile(stock_home, isolated_home)
    if name is None:
        _migrate_marathon_sessions(stock_home, isolated_home)
    return isolated_home, SHARED_PROFILE


def codex_environment(
    environment: Mapping[str, str] | None = None,
    instance: str | None = None,
) -> tuple[dict[str, str], Path, str | None]:
    """Return a child environment configured for Marathon's Codex state."""

    child = dict(os.environ if environment is None else environment)
    home, profile = prepare_codex_home(child, instance)
    child["CODEX_HOME"] = str(home)
    child["MARATHON_LOCAL_ONLY"] = "1"
    for key in ("OPENAI_API_KEY", "CODEX_API_KEY", "OPENAI_ORG_ID", "OPENAI_ORGANIZATION"):
        child.pop(key, None)
    if profile is not None:
        child["CODEX_SQLITE_HOME"] = str(home)
    return child, home, profile


if __name__ == "__main__":
    home, profile = prepare_codex_home()
    print(f"{home}\t{profile or ''}")
